version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
  node: circleci/node@1.1.6

workflows:
  build-test:
    jobs:
      - checkout_and_install
      - build-kovan:
          requires:
            - checkout_and_install
      - build-ropsten:
          requires:
            - checkout_and_install
      - build-mainnet:
          requires:
            - checkout_and_install

jobs:
  checkout_and_install:
    working_directory: ~/gamma-subgraph
    docker:
      - image: circleci/node:10.18.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install packages
          command: npm install
      - save_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - save_cache:
          key: subgraph-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/gamma-subgraph

  build-kovan:
    working_directory: ~/gamma-subgraph
    docker:
      - image: circleci/node:10.18.0
    steps:
      - checkout
      - restore_cache:
          key: gamma-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install packages
          command: npm install
      - run: 
          name: Generate Config
          command: npm run prepare:kovan
      - run:
          name: Code Gen
          command: npm run codegen
      - run:
          name: Build Subgraph
          command: npm run build
      - save_cache:
          key: gamma-contracts-build-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/gamma-subgraph
            
  build-ropsten:
    working_directory: ~/gamma-subgraph
    docker:
      - image: circleci/node:10.18.0
    steps:
      - checkout
      - restore_cache:
          key: gamma-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install packages
          command: npm install
      - run: 
          name: Generate Config
          command: npm run prepare:ropsten
      - run:
          name: Code Gen
          command: npm run codegen
      - run:
          name: Build Subgraph
          command: npm run build
      - save_cache:
          key: gamma-contracts-build-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/gamma-subgraph

  build-mainnet:
    working_directory: ~/gamma-subgraph
    docker:
      - image: circleci/node:10.18.0
    steps:
      - checkout
      - restore_cache:
          key: gamma-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install packages
          command: npm install
      - run: 
          name: Generate Config
          command: npm run prepare:mainnet
      - run:
          name: Code Gen
          command: npm run codegen
      - run:
          name: Build Subgraph
          command: npm run build
      - save_cache:
          key: gamma-contracts-build-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/gamma-subgraph